version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
    networks:
      - app

networks:
  app:

